### ISSUE TITLE
put your script in the end of body and write function in separate file and invoked it 

### ISSUE THREAD

**Issue by ismail2009** [FACG4/IRMS#20]
![screenshot_3](https://user-images.githubusercontent.com/29161826/37447515-17ecc440-282b-11e8-96a7-b242962965e6.png)
![screenshot_4](https://user-images.githubusercontent.com/29161826/37447552-4ca565ac-282b-11e8-902f-1d3f9b17377d.png)

**Comment by MohammedYehia** [comment]
For the first not you should review the font awesome site which suggest that we use their script in the < head > tag 
--

![screenshot from 2018-03-15 10-27-03](https://user-images.githubusercontent.com/7594617/37451955-dd82c4e2-283b-11e8-884d-29fd78af44a0.png)
