### ISSUE TITLE
Html Checker

### ISSUE THREAD

**Issue by mrm7moud** [FACG4/IRMS#22]
This tool is an ongoing experiment in better HTML checking and you have some Error and Warning look at the photo down
https://validator.w3.org/nu/#textarea

![html](https://user-images.githubusercontent.com/3719666/37448778-72441808-2830-11e8-9007-52558c96e315.PNG)

**Comment by RamyAlshurafa** [comment]
thanks !
it's done 
Document checking completed. No errors or warnings to show.
