### ISSUE TITLE
accessibility

### ISSUE THREAD

**Issue by hshahwan** [FACG4/IRMS#32]
Good guys 
![screenshot from 2018-03-15 09-42-53](https://user-images.githubusercontent.com/32449667/37450132-73d62418-2835-11e8-82c1-0eac3856da74.png)

**Comment by MohammedYehia** [comment]
maybe you should update your chrome 

![accessibility](https://user-images.githubusercontent.com/7594617/37452537-905f20e6-283d-11e8-84cd-358c9dc6eb1b.png)
